Import required libraries


In [1]:
import numpy as np
import pandas as pd

In [2]:
data=np.array([[3,7],
               [-4,-6],
               [1,-1],
               [7,8],
               [-4,-1],
               [-3,-7]])

In [3]:
dataframe =pd.DataFrame(data,columns=['x1','x2'])

In [4]:
dataframe

x1  x2
0   3   7
1  -4  -6
2   1  -1
3   7   8
4  -4  -1
5  -3  -7

Next steps:

1.To check whether Data is in Normal Standard form

Standard Normal Form : A data is said to be in Normal Standard for if Mean =0 and Standard Deviation =1


In [6]:
#to check if the data is in the Normal Standard form
dataframe.describe()

x1        x2
count  6.000000  6.000000
mean   0.000000  0.000000
std    4.472136  6.324555
min   -4.000000 -7.000000
25%   -3.750000 -4.750000
50%   -1.000000 -1.000000
75%    2.500000  5.000000
max    7.000000  8.000000

In [9]:
#Since we see that mean is not Eqaul to 1 ,we do the preproceesing to get the Normal Data
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
datascaled=scaler.fit_transform(dataframe)
dataframe =pd.DataFrame(datascaled,columns=['x1','x2'])

In [10]:
dataframe.describe()

x1        x2
count  6.000000e+00  6.000000
mean   1.850372e-17  0.000000
std    1.095445e+00  1.095445
min   -9.797959e-01 -1.212436
25%   -9.185587e-01 -0.822724
50%   -2.449490e-01 -0.173205
75%    6.123724e-01  0.866025
max    1.714643e+00  1.385641

2.Correlation between the Matrix that we have

Difference between Covariance matrix Vs Correlation matrix
--+ve Covariance -> if F1 increases  then F2 also increases
---ve Covariance -> if F1 decreases then F2 increses or Vice versa
---0  F1 and F2 are not in relationship with each other
===Covraince does not have any specific Range====

------------Correlation matrix-----------------
--- -ve Correlation -> indicates the value is close to -1
--- +ve Correlation -> indicates the value is close to +1

Covariance Matrix  gives the accurate Value(it is scaled value)
Correlation Matrix gives the Strength of the Relation ship


**Creating the Coraviance matrix**

In [12]:
#Approach #1
c1=dataframe.x1
c2=dataframe.x2
np.cov(c1,c2) #Evaluate the Covariance matrix

array([[1.2       , 1.06066017],
       [1.06066017, 1.2       ]])

In [13]:
#approach #2
covarianceMatrix=dataframe.T @ dataframe / 5 #(here 5= #of datapoints - 1 )


In [14]:
covarianceMatrix

x1       x2
x1  1.20000  1.06066
x2  1.06066  1.20000

In [15]:
#Approach #3
np.sum(c1 * c2)/5

np.float64(1.0606601717798212)

**Step 3.Evaluate the Eigen Values and Eigen Vectors of the above Correlation Matrix

Using eigenValues and eigenVectors Principal Components are created
1.Higest eigenValue indicates the highest Information

Example :- PC1 will be with the highest eigenValue**

In [17]:
eigenValues,eigenVectors=np.linalg.eig(covarianceMatrix)

In [18]:
eigenValues

array([2.26066017, 0.13933983])

In [19]:
eigenVectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [21]:
eigenVectors[:,0] #0th column

array([0.70710678, 0.70710678])

In [23]:
eigenVectors[:,1]#1st Column

array([-0.70710678,  0.70710678])

In [25]:
#PC1 contains the mximum information of the original two features that you have
PC1 =dataframe @ eigenVectors[:,0]
PC1

0    1.376937
1   -1.427667
2    0.050731
3    2.192231
4   -0.815295
5   -1.376937
dtype: float64

In [26]:
PC2 =dataframe @ eigenVectors[:,1]
PC2

0    0.337706
1   -0.042027
2   -0.295680
3   -0.232640
4    0.570346
5   -0.337706
dtype: float64